server:
  port: 9081

spring:
  application:
    name: service-producer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  sleuth:
    baggage:
      remote-fields:
        - userId
        - userName