server:
  port: 9080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: service-producer-route
          uri: lb://service-producer
          predicates:
            - Path=/service-producer/**
          filters:
            - StripPrefix=1
        - id: service-consumer-route
          uri: lb://service-consumer
          predicates:
            - Path=/service-consumer/**
          filters:
            - StripPrefix=1

