server:
  port: 9082

spring:
  application:
    name: service-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  sleuth:
    baggage:
      remote-fields:
        - userId
        - userName

feign:
  client:
    config:
      service-producer:
        loggerLevel: basic
        read-timeout: 1000

logging:
  level:
    com.wangtao: debug